// <auto-generated />
namespace ProjetoAr3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class bug2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bug2));
        
        string IMigrationMetadata.Id
        {
            get { return "201907092005164_bug2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
