// <auto-generated />
namespace ProjetoAr3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class teste46 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(teste46));
        
        string IMigrationMetadata.Id
        {
            get { return "201907312013219_teste46"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
